name: 测试

on: push

permissions:
  contents: write

jobs:
  job1:
    name: 工作1
    runs-on: ubuntu-latest

    steps:
      - name: 读取
        uses: actions/checkout@v4

      - name: 操作
        run: python md2json.py

      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name yzyyz1387          
          git add .
          git commit -m "update JSON file"
      - name: pushChanges
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.TEST_TOKEN}}


